version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - 80:80
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      DB_CONNECTION: mysql
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
